# Generated by Django 2.1.3 on 2018-11-04 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('maxpersonas', models.CharField(max_length=30)),
                ('camabb', models.CharField(max_length=20)),
                ('bano', models.CharField(max_length=15)),
                ('balcon', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.Habitacion')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.Huesped')),
            ],
        ),
        migrations.AddField(
            model_name='huesped',
            name='habitaciones',
            field=models.ManyToManyField(through='reservaciones.Reserva', to='reservaciones.Habitacion'),
        ),
    ]
