# Generated by Django 2.1.3 on 2018-11-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='telefono',
            field=models.CharField(default=123, max_length=8),
            preserve_default=False,
        ),
    ]
