# Generated by Django 2.1.3 on 2018-11-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0002_huesped_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
