# Generated by Django 2.1.3 on 2018-11-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0003_huesped_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
