# Generated by Django 2.1.3 on 2018-11-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0004_reserva_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_publicacions',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
