# Generated by Django 2.1.3 on 2018-11-05 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0006_habitacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_publicacions',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
