# Generated by Django 2.1.3 on 2018-11-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0007_auto_20181105_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huesped',
            old_name='fecha_publicacion',
            new_name='fechaH',
        ),
    ]
